Vagrant::Config.run do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "../../"
    chef.add_recipe "chef-layerx"
    chef.log_level = :debug
  end
end
