Vagrant.configure("2") do |config|
  config.berkshelf.enabled = true
  config.berkshelf.berksfile_path ="./Berksfile"

  # Set the version of chef to install using the vagrant-omnibus plugin
  # NOTE: You will need to install the vagrant-omnibus plugin:
  #
  #   $ vagrant plugin install vagrant-omnibus
  #
  if Vagrant.has_plugin?("vagrant-omnibus")
    config.omnibus.chef_version = 'latest'
  end

  config.omnibus.chef_version = :latest

  # vbox config
  config.vm.provider :virtualbox do |vb, override|
    vb.name = 'vagrant-layer-x'

    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", "#{1024*1}"]
    vb.customize ["modifyvm", :id,  "--cpus",  "1"]

    # please customize hostname and private ip configuration if you needed.
    override.vm.hostname = "layer-x"
    private_ip = "192.168.33.10"
    override.vm.network :private_network, ip: private_ip
    override.vm.provision :hosts do |provisioner|
      provisioner.add_host private_ip , [ config.vm.hostname ]
    end
  end

end

Vagrant::Config.run do |runconfig|
  runconfig.vm.box = "ubuntu/trusty64"
  runconfig.vm.provision :chef_solo do |chef|
    chef.add_recipe "apt"
    chef.add_recipe "golang"
    chef.add_recipe "golang::packages"
    chef.add_recipe "layerx"
    chef.log_level = :debug
    chef.json = {
      :go => {
        :version => "1.7",
        :owner => "vagrant",
        :group => "vagrant",
        :packages => [
          "github.com/jteeuwen/go-bindata/...",
          "github.com/elazarl/go-bindata-assetfs/..."
        ]
      },
      :layerx => {
        :user => "vagrant",
        :group => "vagrant",
      }
    }
  end

end
