Vagrant.configure("2") do |config|
  config.berkshelf.enabled = true
  config.berkshelf.berksfile_path ="./Berksfile"

  # Set the version of chef to install using the vagrant-omnibus plugin
  # NOTE: You will need to install the vagrant-omnibus plugin:
  #
  #   $ vagrant plugin install vagrant-omnibus
  #
  if Vagrant.has_plugin?("vagrant-omnibus")
    config.omnibus.chef_version = 'latest'
  end

  config.omnibus.chef_version = :latest
end

Vagrant::Config.run do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision :chef_solo do |chef|
    chef.add_recipe "golang::packages"
    chef.add_recipe "layerx"
    chef.log_level = :debug
    chef.json = {
      :go => {
        :packages => [
          "github.com/jteeuwen/go-bindata/...",
          "github.com/elazarl/go-bindata-assetfs/..."
        ]
      }
    }
  end
end
